#!/usr/bin/env python3
"""Generate the prompt-embeddable `(source, canonical)` example pack
for the foundation/objects primitive.

For each fixture in this directory, extract the raw bytes of each
`N M obj ... endobj` block and pair it with the matching line in
the fixture's `.canonical` sidecar. The result is a markdown block
that can be injected into the composer prompt so the LLM sees real
PDF source → expected canonical output instead of inferring the
mapping from prose.

Input licensing: all fixtures are hand-authored here, the
`.canonical` sidecars were generated by oracle agreement (qpdf +
mutool producing byte-identical output). No oracle source code is
included — only outputs, which are re-emissions of our own input
fixtures.

Run directly to preview::

    python3 example_pack.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent


# Match an indirect-object block. Non-greedy body so we stop at the
# FIRST ``endobj`` — stream bodies with raw bytes might contain the
# literal word "endobj" in theory but our fixtures don't, so the
# simple greedy-stop is safe for the example pack.
_OBJ_RE = re.compile(
    rb"(\d+)\s+(\d+)\s+obj\b([\s\S]*?)\bendobj\b",
    re.MULTILINE,
)


def extract_objects(pdf_bytes: bytes) -> list[tuple[int, int, str]]:
    """Return (id, gen, raw_source) for every indirect-object block.

    ``raw_source`` is the ``N M obj ... endobj`` block as text, with
    the terminating ``endobj`` included and CR/LF normalised to LF
    so it renders predictably inside a markdown code fence. Binary
    stream bodies are preserved as-is (we don't re-encode); if a
    fixture contains a truly binary object its source text won't
    round-trip as UTF-8 and the renderer marks it with a short note
    instead of dumping the bytes.
    """
    out: list[tuple[int, int, str]] = []
    for m in _OBJ_RE.finditer(pdf_bytes):
        oid = int(m.group(1))
        gen = int(m.group(2))
        start = m.start()
        end = m.end()
        block = pdf_bytes[start:end]
        try:
            text = block.decode("utf-8")
        except UnicodeDecodeError:
            # Stream object with non-UTF-8 body — skip the body but
            # keep the header dict for the example, with a marker.
            header_end = block.find(b"stream")
            if header_end >= 0:
                text = (block[:header_end].decode(
                            "utf-8", errors="replace")
                        + "stream\n<< binary body, "
                        + str(end - start - header_end - 6)
                        + " bytes >>\nendstream\nendobj")
            else:
                text = block.decode("utf-8", errors="replace")
        out.append((oid, gen, text.replace("\r\n", "\n").replace("\r", "\n")))
    out.sort(key=lambda r: (r[0], r[1]))
    return out


def load_canonical_map(canonical_path: Path) -> dict[tuple[int, int], str]:
    """Parse a `.canonical` sidecar into a {(id, gen): canonical_line} map.

    Each line is ``<id> <gen> <value_canonical>`` — everything after
    the first two whitespace-separated tokens is the value portion.
    """
    out: dict[tuple[int, int], str] = {}
    for line in canonical_path.read_text().splitlines():
        if not line.strip():
            continue
        parts = line.split(None, 2)
        if len(parts) < 3:
            # Value-less entries (e.g. bare `null`) have form "<id> <gen> null"
            # with 3 parts, so this branch handles genuinely malformed lines.
            continue
        oid = int(parts[0])
        gen = int(parts[1])
        out[(oid, gen)] = parts[2]
    return out


def render_fixture_block(pdf_path: Path, max_objects: int | None = None) -> str:
    """Render one fixture's worth of (source, canonical) pairs as
    markdown. Objects are listed in id order; ``max_objects`` caps
    the output so no single fixture dominates the prompt.
    """
    canonical_path = pdf_path.with_suffix(".canonical")
    if not canonical_path.is_file():
        return ""
    pdf_bytes = pdf_path.read_bytes()
    objects = extract_objects(pdf_bytes)
    canonical_map = load_canonical_map(canonical_path)

    lines: list[str] = [f"### Fixture: `{pdf_path.name}`\n"]
    emitted = 0
    for (oid, gen, source) in objects:
        canonical = canonical_map.get((oid, gen))
        if canonical is None:
            continue
        lines.append(
            f"Source (object {oid} {gen}):\n"
            f"```\n{source.rstrip()}\n```\n"
            f"Canonical output for this object:\n"
            f"```\n{oid} {gen} {canonical}\n```\n")
        emitted += 1
        if max_objects is not None and emitted >= max_objects:
            break
    return "\n".join(lines)


# Per-fixture caps keep the pack small enough to fit the prompt
# while still covering every primitive kind + a representative
# composite and stream case. Tuned empirically against the reference
# context window; lift if a better LLM is swapped in.
_FIXTURE_ORDER = [
    ("primitives.pdf",    14),   # one obj per primitive kind — full set
    ("nested.pdf",         4),   # 2 composite + 1 mixed-ref cases
    ("stream.pdf",         2),   # the stream object (+ one direct obj)
    ("edge_escapes.pdf",   4),   # string/name escape edge cases
    ("number_edges.pdf",   4),   # numeric edge cases
]


def render_pack() -> str:
    """Render the full example pack as one markdown block ready to
    paste into a prompt. Fixtures are laid out in ``_FIXTURE_ORDER``
    so the LLM reads simple cases first and composites later."""
    blocks: list[str] = [
        "**Corpus-driven canonical-form examples** — each block below "
        "shows real PDF source bytes (left) and the freeze-gate "
        "canonical line the primitive must produce (right). These "
        "were generated from committed fixtures and their oracle-"
        "agreed sidecars; they are the CONTRACT.\n"
    ]
    for fname, cap in _FIXTURE_ORDER:
        pdf_path = HERE / fname
        if not pdf_path.is_file():
            continue
        blocks.append(render_fixture_block(pdf_path, max_objects=cap))
    return "\n".join(blocks)


if __name__ == "__main__":
    sys.stdout.write(render_pack())
