#!/usr/bin/env python3
"""One-shot generator for standard14_outlines_bundle.inc.

Reads the 12 Liberation TTF binaries in this directory and emits
a C++20 compile-time data table consumed by
src/internal/standard14_outlines.cpp.

Idempotent. Run whenever upstream Liberation Fonts bumps version.

Usage (run from this directory or anywhere — paths are resolved
from this script's location):
    python3 standard14_outlines.py <output-file>
    python3 standard14_outlines.py > <output-file>     # also OK

When argv[1] is absent the script writes to stdout (legacy mode).
When supplied, the script opens that path for writing — this is
the path the CMake build uses, since shell redirection in
add_custom_command isn't reliably portable across all
generator + host-shell combinations (notably Windows MSBuild
under Visual Studio's CMake integration).

The CMake build system invokes this script at build-time through
an add_custom_command in the lib's top-level CMakeLists.

Liberation 2.1.5 release URL:
    https://github.com/liberationfonts/liberation-fonts/files/
    7261482/liberation-fonts-ttf-2.1.5.tar.gz
"""
from __future__ import annotations

import datetime
import os
import sys

# Standard14 PostScript font name -> bundled Liberation TTF
# filename (in this directory). Symbol + ZapfDingbats have no
# bundled substitute (Liberation doesn't cover them and there's
# no permissively-licensed metric-equivalent); their bundle
# entries are absent and Resolve() falls through to empty bytes.
STANDARD14_TO_LIBERATION = {
    "Helvetica":              "LiberationSans-Regular.ttf",
    "Helvetica-Bold":         "LiberationSans-Bold.ttf",
    "Helvetica-Oblique":      "LiberationSans-Italic.ttf",
    "Helvetica-BoldOblique":  "LiberationSans-BoldItalic.ttf",
    "Times-Roman":            "LiberationSerif-Regular.ttf",
    "Times-Bold":             "LiberationSerif-Bold.ttf",
    "Times-Italic":           "LiberationSerif-Italic.ttf",
    "Times-BoldItalic":       "LiberationSerif-BoldItalic.ttf",
    "Courier":                "LiberationMono-Regular.ttf",
    "Courier-Bold":           "LiberationMono-Bold.ttf",
    "Courier-Oblique":        "LiberationMono-Italic.ttf",
    "Courier-BoldOblique":    "LiberationMono-BoldItalic.ttf",
}


def emit_byte_array(name: str, data: bytes, out) -> None:
    out.write(f"\nconstexpr std::array<std::uint8_t, {len(data)}> "
              f"{name} = {{\n")
    # 16 bytes per line, hex.
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        out.write("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",\n")
    out.write("};\n")


def main() -> int:
    # Script lives alongside the TTFs (src/internal/standard14_outlines.fonts/),
    # so this directory IS fonts_dir.
    fonts_dir = os.path.dirname(os.path.abspath(__file__))

    # argv[1] (when present) is the destination path; otherwise
    # write to stdout so old `python3 … > file` invocations keep
    # working.
    out_path = sys.argv[1] if len(sys.argv) > 1 else None
    out = open(out_path, "w", encoding="utf-8") if out_path else sys.stdout
    try:
        return _emit(fonts_dir, out)
    finally:
        if out_path:
            out.close()


def _emit(fonts_dir: str, out) -> int:
    out.write(f"// AUTO-GENERATED by src/internal/standard14_outlines.fonts/standard14_outlines.py at "
              f"{datetime.datetime.now(datetime.timezone.utc).isoformat()}\n"
              f"// DO NOT EDIT BY HAND.\n"
              f"//\n"
              f"// Source: Liberation Fonts 2.1.5\n"
              f"// (github.com/liberationfonts/liberation-fonts).\n"
              f"// License: SIL Open Font License v1.1 — see\n"
              f"// OFL.txt next to this generator.\n\n")

    arrays: list[tuple[str, str]] = []  # (postscript_name, c_var_name)
    for ps_name, fn in STANDARD14_TO_LIBERATION.items():
        path = os.path.join(fonts_dir, fn)
        if not os.path.exists(path):
            print(f"ERROR: missing bundled font: {path}", file=sys.stderr)
            return 2
        with open(path, "rb") as fp:
            data = fp.read()
        # Sanity: TTF magic (00 01 00 00) or OpenType (4F 54 54 4F).
        if data[:4] not in (b"\x00\x01\x00\x00", b"OTTO"):
            print(f"ERROR: {fn} is not TTF/OTF (magic={data[:4]!r})",
                  file=sys.stderr)
            return 3
        c_var = "kFont_" + ps_name.replace("-", "_")
        emit_byte_array(c_var, data, out)
        arrays.append((ps_name, c_var))

    # Emit the lookup table as a constexpr std::array of pairs.
    out.write("\nstruct BundleEntry {\n"
              "    std::string_view name;\n"
              "    std::span<const std::uint8_t> data;\n"
              "};\n")
    out.write(f"\nconstexpr std::array<BundleEntry, {len(arrays)}> "
              f"kBundle = {{{{\n")
    for ps, var in arrays:
        out.write(f"    {{\"{ps}\", {var}}},\n")
    out.write("}};\n")

    return 0


if __name__ == "__main__":
    sys.exit(main())
