// Body for foundation::agl. See agl.hpp for the contract +
// the AGL §4 fallback rules. Pure-data lookup; the table is
// in agl_data.inc, regenerated by generate_data.py from
// pdfminer.six's glyphname2unicode (Adobe Glyph List).

#include "agl.hpp"

#include <algorithm>
#include <array>
#include <cstddef>
#include <cstdint>

namespace foundation::agl {

namespace {

#include "agl_data.inc"

// Cached Entry view over the static table — built lazily on
// first call to StaticEntries() so the constexpr-initialised
// arrays above don't pay for a second copy at static init.
const Entry* GetEntries() noexcept {
    static const auto kEntries = []() {
        std::array<Entry, kAglRowCount> arr{};
        for (std::size_t i = 0; i < kAglRowCount; ++i) {
            const auto& r = kAglRows[i];
            arr[i].name = std::string_view(r.name);
            arr[i].codepoints = std::span<const std::uint32_t>(
                kAglCodepointPool + r.cp_offset, r.cp_count);
        }
        return arr;
    }();
    return kEntries.data();
}

bool IsHexDigit(char c) noexcept {
    return (c >= '0' && c <= '9') ||
           (c >= 'a' && c <= 'f') ||
           (c >= 'A' && c <= 'F');
}

int HexValue(char c) noexcept {
    if (c >= '0' && c <= '9') return c - '0';
    if (c >= 'a' && c <= 'f') return 10 + (c - 'a');
    return 10 + (c - 'A');
}

bool IsSurrogate(std::uint32_t cp) noexcept {
    return cp >= 0xD800 && cp <= 0xDFFF;
}

// Binary search by name. Returns nullptr when not present.
const AglRow* FindRow(std::string_view name) noexcept {
    const auto* first = kAglRows;
    const auto* last = kAglRows + kAglRowCount;
    auto it = std::lower_bound(
        first, last, name,
        [](const AglRow& row, std::string_view n) {
            return std::string_view(row.name) < n;
        });
    if (it == last) return nullptr;
    if (std::string_view(it->name) != name) return nullptr;
    return it;
}

// Recognise "uniHHHH..." — 4-hex-digit groups, BMP only.
// Returns true and appends codepoints on success; false on
// any malformed input (odd hex length, non-hex digit, group
// is a surrogate). All-or-nothing — partial inputs return
// false without mutating `out`.
bool ParseUniGroups(std::string_view rest,
                    std::vector<std::uint32_t>& out) noexcept {
    if (rest.empty()) return false;
    if (rest.size() % 4 != 0) return false;
    std::vector<std::uint32_t> tmp;
    tmp.reserve(rest.size() / 4);
    for (std::size_t i = 0; i < rest.size(); i += 4) {
        std::uint32_t cp = 0;
        for (int j = 0; j < 4; ++j) {
            const char c = rest[i + j];
            if (!IsHexDigit(c)) return false;
            cp = (cp << 4) | static_cast<std::uint32_t>(HexValue(c));
        }
        if (IsSurrogate(cp)) return false;
        tmp.push_back(cp);
    }
    out.insert(out.end(), tmp.begin(), tmp.end());
    return true;
}

// Recognise "uHHHHHH" — 4 to 6 hex digits, any plane,
// surrogates rejected.
bool ParseUSingle(std::string_view rest,
                  std::vector<std::uint32_t>& out) noexcept {
    if (rest.size() < 4 || rest.size() > 6) return false;
    std::uint32_t cp = 0;
    for (char c : rest) {
        if (!IsHexDigit(c)) return false;
        cp = (cp << 4) | static_cast<std::uint32_t>(HexValue(c));
    }
    if (IsSurrogate(cp)) return false;
    if (cp > 0x10FFFF) return false;
    out.push_back(cp);
    return true;
}

// Look up one component (no underscores). Applies the dot-
// suffix strip and the uni*/u* fallbacks.
bool LookupComponent(
        std::string_view name,
        std::vector<std::uint32_t>& out) noexcept {
    // §4.1: drop everything from the first dot.
    if (auto dot = name.find('.'); dot != std::string_view::npos) {
        name = name.substr(0, dot);
    }
    if (name.empty()) return false;

    // §4.2 / 4.3: the static AGL table.
    if (const auto* row = FindRow(name); row != nullptr) {
        for (std::size_t i = 0; i < row->cp_count; ++i) {
            out.push_back(kAglCodepointPool[row->cp_offset + i]);
        }
        return true;
    }

    // §4.4: uniXXXX[XXXX...] — BMP-only, 4-digit groups.
    if (name.starts_with("uni")) {
        return ParseUniGroups(name.substr(3), out);
    }

    // §4.5: uXXXX..XXXXXX — single, 4-6 hex digits, any plane.
    if (name.starts_with("u") && name.size() > 1) {
        return ParseUSingle(name.substr(1), out);
    }

    return false;
}

}  // anonymous namespace

std::vector<std::uint32_t> Lookup(
        std::string_view glyph_name) noexcept {
    std::vector<std::uint32_t> out;
    if (glyph_name.empty()) return out;

    // §4: split on '_' for compound (ligature) names. We
    // recurse via LookupComponent for each piece. If ANY
    // component fails to resolve, the whole lookup returns
    // empty — partial decoding would be wrong (the AGL spec
    // is all-or-nothing on compound names).
    std::size_t start = 0;
    while (start <= glyph_name.size()) {
        const std::size_t under =
            glyph_name.find('_', start);
        const std::string_view comp =
            glyph_name.substr(
                start,
                under == std::string_view::npos
                    ? std::string_view::npos
                    : under - start);
        std::vector<std::uint32_t> piece;
        if (!LookupComponent(comp, piece)) {
            return {};
        }
        out.insert(out.end(), piece.begin(), piece.end());
        if (under == std::string_view::npos) break;
        start = under + 1;
    }
    return out;
}

std::span<const Entry> StaticEntries() noexcept {
    static const Entry* base = GetEntries();
    return std::span<const Entry>(base, kAglRowCount);
}

}  // namespace foundation::agl
