// Body for foundation::encoding_tables. See encoding_tables.hpp
// for the contract. Pure-data lookup — the static tables are
// in encoding_tables_data.inc, regenerated by generate_data.py
// from pdfminer.six's master encoding list.

#include "encoding_tables.hpp"

#include <array>
#include <cstddef>
#include <cstdint>

namespace foundation::encoding_tables {

namespace {

#include "encoding_tables_data.inc"

constexpr const char* const* TableForEncoding(
        Encoding e) noexcept {
    switch (e) {
        case Encoding::StandardEncoding:
            return kStandardEncodingTable;
        case Encoding::MacRomanEncoding:
            return kMacRomanEncodingTable;
        case Encoding::WinAnsiEncoding:
            return kWinAnsiEncodingTable;
        case Encoding::PDFDocEncoding:
            return kPDFDocEncodingTable;
    }
    return kStandardEncodingTable;
}

}  // anonymous namespace

std::string_view ByteToGlyphName(
        Encoding encoding, std::uint8_t code) noexcept {
    return std::string_view(TableForEncoding(encoding)[code]);
}

std::span<const std::string_view> Table(
        Encoding encoding) noexcept {
    // Build a per-encoding cached array of string_views over
    // the raw const char* slots. The cache is built lazily on
    // first call and stored in static storage; subsequent
    // calls are O(1).
    auto build = [](const char* const* src) {
        std::array<std::string_view, 256> arr{};
        for (std::size_t i = 0; i < 256; ++i) {
            arr[i] = std::string_view(src[i]);
        }
        return arr;
    };
    static const auto kStd  = build(kStandardEncodingTable);
    static const auto kMac  = build(kMacRomanEncodingTable);
    static const auto kWin  = build(kWinAnsiEncodingTable);
    static const auto kPdfD = build(kPDFDocEncodingTable);
    switch (encoding) {
        case Encoding::StandardEncoding:
            return std::span<const std::string_view>(
                kStd.data(), kStd.size());
        case Encoding::MacRomanEncoding:
            return std::span<const std::string_view>(
                kMac.data(), kMac.size());
        case Encoding::WinAnsiEncoding:
            return std::span<const std::string_view>(
                kWin.data(), kWin.size());
        case Encoding::PDFDocEncoding:
            return std::span<const std::string_view>(
                kPdfD.data(), kPdfD.size());
    }
    return std::span<const std::string_view>(
        kStd.data(), kStd.size());
}

std::optional<Encoding> EncodingFromName(
        std::string_view name) noexcept {
    if (name == "StandardEncoding")
        return Encoding::StandardEncoding;
    if (name == "MacRomanEncoding")
        return Encoding::MacRomanEncoding;
    if (name == "WinAnsiEncoding")
        return Encoding::WinAnsiEncoding;
    if (name == "PDFDocEncoding")
        return Encoding::PDFDocEncoding;
    return std::nullopt;
}

}  // namespace foundation::encoding_tables
