#!/usr/bin/env python3
"""Generate the JPEG fixture corpus + .pixels sidecars for the
foundation/dctdecode primitive.

Each fixture is a (small, deterministic) JPEG file produced by Pillow
from a synthetic source pattern; the matching `.pixels` sidecar is
the oracle-authored RGBA8 pixel buffer the freeze-gate driver
compares against by PSNR. Fixtures and sidecars are public-domain —
the only inputs are integers from this file.

Pipeline per fixture:

  1. Pillow builds a source RGB (or L-grayscale) image from a
     deterministic pattern function.
  2. Pillow saves it as a JPEG (`<name>.jpg`) using the chosen
     subsampling / progressive / quality settings. Optimize=False
     and no metadata writes — the output bytes must be reproducible
     so the corpus can be regenerated byte-for-byte from this script.
  3. `djpeg -rgb -pnm <name>.jpg` decodes the JPEG to a PPM byte
     stream. `-rgb` forces 3-channel output even when the input
     JPEG is grayscale (libjpeg-turbo replicates Y into R=G=B), so
     the sidecar shape is always `width*height*4` RGBA bytes
     regardless of the source's color space — matching our
     adapter's `JCS_EXT_RGBA` output.
  4. Pillow reads the PPM bytes, converts to RGBA (which only
     appends a 0xFF alpha byte per pixel — no color math), and we
     write the raw buffer to `<name>.pixels`.

djpeg is the declared oracle (see dctdecode.shared.yaml). Pillow is
used only for PPM parsing + RGB→RGBA widening in step 4; no JPEG
decode work goes through Pillow here.

Run from this directory:
    python3 generate_fixtures.py
"""

from __future__ import annotations

import hashlib
import io
import subprocess
from pathlib import Path

# Pillow is used for (a) source-image authoring and (b) PPM parsing
# + RGBA widening. Pillow's JPEG decode path is NOT on the oracle
# pipeline — djpeg is. If Pillow isn't installed the script should
# fail loudly with a clear message at import time; this is a build-
# time tool, not a library.
from PIL import Image


# ---------------------------------------------------------------------------
# Source-image authoring
# ---------------------------------------------------------------------------


def _solid_red(w: int, h: int) -> Image.Image:
    """Solid-red fill — the trivial decode. Any byte-level error in
    channel order, stride, or dimensions shows up as a non-red pixel
    in the decoded output. A JPEG of a solid-color image also
    compresses to a small deterministic byte stream, so this fixture
    stays tiny on disk."""
    return Image.new("RGB", (w, h), (255, 0, 0))


def _horizontal_gradient(w: int, h: int) -> Image.Image:
    """Horizontal R=x gradient, G=B=0. Exposes chroma-subsampling
    effects: at 4:2:0 (quality 85) the reconstructed gradient has
    subtle color drift from chroma interpolation — the PSNR gate
    absorbs that. A stride bug would manifest as vertical banding
    in the PSNR comparison."""
    img = Image.new("RGB", (w, h))
    pixels = img.load()
    for y in range(h):
        for x in range(w):
            v = int(255 * x / max(1, w - 1))
            pixels[x, y] = (v, 0, 0)
    return img


def _checkerboard(w: int, h: int, cell: int) -> Image.Image:
    """Black/white checkerboard — high-frequency content that
    stresses the IDCT. Chroma-subsampled JPEG of a checkerboard
    ringing artefacts at block boundaries; the PSNR gate at
    50 dB tolerates them. A mis-ordered colour channel would
    show up as non-gray output pixels here (the source has
    R=G=B at every pixel)."""
    img = Image.new("RGB", (w, h))
    pixels = img.load()
    for y in range(h):
        for x in range(w):
            on = ((x // cell) + (y // cell)) % 2 == 0
            pixels[x, y] = (255, 255, 255) if on else (0, 0, 0)
    return img


def _gray_ramp(w: int, h: int) -> Image.Image:
    """Grayscale horizontal ramp. The JPEG is written in `L` mode
    which libjpeg encodes as a 1-component (grayscale) stream; our
    adapter + djpeg both widen this to RGBA by replicating the Y
    value into R=G=B. Stresses the grayscale-input → RGBA-output
    path that a wrong `JCS_EXT_RGBA` request (or missing component
    count handling) would break."""
    img = Image.new("L", (w, h))
    pixels = img.load()
    for y in range(h):
        for x in range(w):
            pixels[x, y] = int(255 * x / max(1, w - 1))
    return img


def _color_bars(w: int, h: int) -> Image.Image:
    """Six vertical color bars (R/G/B/C/M/Y). Exposes colour-channel
    mixups (a swapped R/B would turn the red bar cyan) and reveals
    any off-by-one in column iteration. Moderate frequency content
    — cleaner than a checkerboard, noisier than a gradient."""
    colors = [(255, 0, 0), (0, 255, 0), (0, 0, 255),
              (0, 255, 255), (255, 0, 255), (255, 255, 0)]
    img = Image.new("RGB", (w, h))
    pixels = img.load()
    bar_w = max(1, w // len(colors))
    for y in range(h):
        for x in range(w):
            idx = min(x // bar_w, len(colors) - 1)
            pixels[x, y] = colors[idx]
    return img


def _synthetic_photo(w: int, h: int) -> Image.Image:
    """Smooth deterministic "photographic" content — a sum of three
    2-D sinusoids at different frequencies and channels. Mimics
    natural-image statistics (low-to-mid frequency energy, smooth
    gradients) that real-world DCT coefficients see. Produces a
    midsize JPEG (~2 KiB at quality 75 for 64x64) — bridges the
    "tiny synthetic" and "real photo" ends of the corpus. A
    progressive-encoded variant of the same content is shipped
    separately so progressive-scan decode paths are also tested."""
    import math
    img = Image.new("RGB", (w, h))
    pixels = img.load()
    for y in range(h):
        for x in range(w):
            # Three orthogonal sinusoids keep the spectrum varied
            # without any single dominant frequency — the encoder
            # has to spread energy across DCT coefficients, which
            # is representative of real-photo compression.
            r = 128 + int(60 * math.sin(2 * math.pi * x / 16))
            g = 128 + int(60 * math.sin(2 * math.pi * y / 12))
            b = 128 + int(60 * math.sin(
                2 * math.pi * (x + y) / 20))
            pixels[x, y] = (max(0, min(255, r)),
                            max(0, min(255, g)),
                            max(0, min(255, b)))
    return img


# ---------------------------------------------------------------------------
# Fixture registry — (filename, source-factory, JPEG save kwargs)
# ---------------------------------------------------------------------------


# Pillow JPEG save kwargs reference (see Pillow's JpegImagePlugin):
#   quality     — integer 1..95 (or 'keep' for re-encoded sources)
#   subsampling — 0 (4:4:4), 1 (4:2:2), 2 (4:2:0), -1 (default)
#   progressive — bool; when True, emit a progressive-scan stream
#   optimize    — bool; when True, run an optimal Huffman pass.
#                 Kept OFF everywhere so bytes are deterministic
#                 across Pillow versions with slightly different
#                 optimizer heuristics.
#
# The fixtures aim to exercise orthogonal axes of the decode path:
#   solid_red_16        — baseline 4:4:4, trivial content (sanity)
#   gradient_32         — baseline 4:2:0, smooth chroma content
#   checker_16          — baseline 4:2:0, high-frequency luma
#   gray_32             — baseline grayscale (L-mode encode)
#   progressive_64      — progressive scan, synthetic photo
#   photo_64            — baseline 4:2:0, synthetic photo (matched
#                         partner for progressive_64 — any delta
#                         between the two isolates progressive-scan
#                         decode issues)
#   bars_64             — baseline 4:4:4, six color bars (channel
#                         ordering canary)
_FIXTURES: list[tuple[str, callable, dict]] = [
    ("solid_red_16.jpg",
     lambda: _solid_red(16, 16),
     {"quality": 95, "subsampling": 0, "progressive": False,
      "optimize": False}),
    ("gradient_32.jpg",
     lambda: _horizontal_gradient(32, 32),
     {"quality": 85, "subsampling": 2, "progressive": False,
      "optimize": False}),
    ("checker_16.jpg",
     lambda: _checkerboard(16, 16, 2),
     {"quality": 85, "subsampling": 2, "progressive": False,
      "optimize": False}),
    ("gray_32.jpg",
     lambda: _gray_ramp(32, 32),
     {"quality": 85, "subsampling": 0, "progressive": False,
      "optimize": False}),
    ("bars_64.jpg",
     lambda: _color_bars(64, 16),
     {"quality": 90, "subsampling": 0, "progressive": False,
      "optimize": False}),
    ("photo_64.jpg",
     lambda: _synthetic_photo(64, 64),
     {"quality": 75, "subsampling": 2, "progressive": False,
      "optimize": False}),
    ("progressive_64.jpg",
     lambda: _synthetic_photo(64, 64),
     {"quality": 75, "subsampling": 2, "progressive": True,
      "optimize": False}),
]


# ---------------------------------------------------------------------------
# Oracle pipeline: djpeg -> PPM -> RGBA sidecar
# ---------------------------------------------------------------------------


def _djpeg_to_rgba(jpg_path: Path) -> bytes:
    """Run djpeg on ``jpg_path`` with ``-rgb -pnm`` and return the
    decoded pixels as a raw RGBA8 byte vector (width*height*4 bytes,
    alpha constantly 0xFF).

    ``-rgb`` forces 3-channel RGB output even for grayscale source
    JPEGs; libjpeg-turbo replicates Y into R=G=B, matching what our
    adapter sees when it requests ``JCS_EXT_RGBA`` from a grayscale
    JPEG. ``-pnm`` writes PPM (portable pixmap) — magic ``P6``,
    ASCII header, binary pixel data — which Pillow parses natively.

    We pipe djpeg's output rather than writing a scratch PPM file
    so a generation run leaves no intermediate artefacts behind.
    """
    r = subprocess.run(
        ["djpeg", "-rgb", "-pnm", str(jpg_path)],
        check=True, capture_output=True)
    ppm_bytes = r.stdout
    # Pillow parses PPM without using libjpeg — it's a trivial
    # format (magic + dimensions + maxval + raw bytes). Converting
    # to RGBA only appends a 0xFF alpha after each RGB triple; no
    # color-space math runs, so this step cannot shift pixel values.
    img = Image.open(io.BytesIO(ppm_bytes))
    rgba = img.convert("RGBA")
    return rgba.tobytes()


# ---------------------------------------------------------------------------
# Writer
# ---------------------------------------------------------------------------


def main() -> int:
    here = Path(__file__).parent
    # Fail fast if the declared oracle is missing. The script runs
    # rarely (fixture authoring, not per-test-run), so "install
    # djpeg first" is a reasonable prerequisite rather than a
    # degrade path.
    r = subprocess.run(["djpeg", "-version"],
                       capture_output=True, text=True)
    if r.returncode != 0:
        print("ERROR: djpeg not on PATH — install libjpeg-turbo")
        return 1
    print(f"oracle: djpeg found ({r.stdout.strip() or r.stderr.strip()})")

    for name, make_source, save_kwargs in _FIXTURES:
        jpg_path = here / name
        sidecar_path = jpg_path.with_suffix(".pixels")

        # Encode the synthetic source through Pillow's JPEG writer.
        # Pillow here acts as "any JPEG encoder" — the adapter isn't
        # being tested on Pillow-specific bytes, it's being tested
        # on a JPEG the oracle can decode. The adapter's job is to
        # produce the same pixels djpeg produces.
        src = make_source()
        src.save(jpg_path, format="JPEG", **save_kwargs)
        jpg_bytes = jpg_path.read_bytes()

        # Oracle decode: djpeg produces the reference pixel buffer.
        rgba = _djpeg_to_rgba(jpg_path)
        sidecar_path.write_bytes(rgba)

        jpg_digest = hashlib.sha256(jpg_bytes).hexdigest()[:16]
        px_digest = hashlib.sha256(rgba).hexdigest()[:16]
        print(f"wrote {name:24s} "
              f"{len(jpg_bytes):6d} B jpg (sha256:{jpg_digest}…), "
              f"{len(rgba):7d} B rgba (sha256:{px_digest}…)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
